version: 2.1

description: |
  TODO
examples:
  simple_build_and_scan:
    description: Build and scan a docker image with Aquasec's microscanner
    usage:
      version: 2.1

      orbs:
        microscanner: aquasec/micrscanner@1.0.0

      workflows:
        scan-image:
          jobs:
            - microscanner/build-and-scan:
                context: myContext # your context containing gcloud login variables
                image: my-image # your image name
                tag: latest
                artifact-type: html

executors:
  default:
    description: A debian-based machine executor.  Note that there is an 
                 overhead for provisioning a machine executor as a result of
                 spinning up a private Docker server. Use of the machine key
                 may require additional fees.
    machine: 
      image: circleci/classic:201808-01

commands:
  install:
    description: Install the Aqua microscanner binary
    parameters:
      token:
        description: The Aqua microscanner token
        type: string
        default: $AQUA_TOKEN
    steps:
      - run: |
          git clone git@github.com:lukebond/microscanner-wrapper.git
  scan:
    description: Scan container image
    parameters:
      token:
        description: The Aqua microscanner token
        type: string
        default: $AQUA_TOKEN
      image:
        description: The image to scan
        type: string
      artifact-type:
        description: The type of artifact to output
        type: string
        default: html
    steps:
      - run:
          name: create artifact
          # background: true
          command: |
            mkdir output
            cd microscanner-wrapper
            if [[ <<parameters.artifact-type>> == json ]]; then
              MICROSCANNER_TOKEN=<<parameters.token>> ./grabjson.sh <<parameters.image>> > ../output/output.json
            else
              MICROSCANNER_TOKEN=<<parameters.token>> ./grabhtml.sh <<parameters.image>> > ../output/output.html
            fi
      - store_artifacts:
          path: output

jobs:
  scan-image:
    executor: default
    parameters:
      token:
        description: The Aqua microscanner token
        type: string
        default: $AQUA_TOKEN
      image:
        description: The image to scan
        type: string
      artifact-type:
        description: The type of artifact to output
        type: string
        default: html
      dockerfile-path:
        description: The path to your Dockerfile
        type: string
        default: .
    steps:
      - checkout
      - install 
      - scan:
          image: <<parameters.image>>
